=begin
#Meltwater Streaming API v2

#The Meltwater Streaming API provides the needed resources for Meltwater clients to create & delete REST Hooks and stream Meltwater search results to your specified destination.

OpenAPI spec version: 2.0.0
Contact: support@api.meltwater.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SchemasApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SchemasApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SchemasApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SchemasApi' do
    it 'should create an instact of SchemasApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SchemasApi)
    end
  end

  # unit tests for get_editorial_streaming_json_schema
  # Editorial Streaming JSON schema
  # Get the JSON schema describing the layout of Editorial Streaming documents.
  # @param user_key The &#x60;user_key&#x60; from [developer.meltwater.com](https://developer.meltwater.com/admin/applications/).
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_editorial_streaming_json_schema test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_social_streaming_json_schema
  # Social Streaming JSON schema
  # Get the JSON schema describing the layout of Social Streaming documents.
  # @param user_key The &#x60;user_key&#x60; from [developer.meltwater.com](https://developer.meltwater.com/admin/applications/).
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_social_streaming_json_schema test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
