=begin
#Meltwater Streaming API v2

#The Meltwater Streaming API provides the needed resources for Meltwater clients to create & delete REST Hooks and stream Meltwater search results to your specified destination.

OpenAPI spec version: 2.0.0
Contact: support@api.meltwater.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SwaggerDocApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SwaggerDocApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SwaggerDocApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SwaggerDocApi' do
    it 'should create an instact of SwaggerDocApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SwaggerDocApi)
    end
  end

  # unit tests for get_complete_swagger_spec
  # Meltwater API Swagger Spec
  # Get the complete Swagger Spec that describes all Meltwater API endpoints.
  # @param user_key The &#x60;user_key&#x60; from [developer.meltwater.com](https://developer.meltwater.com/admin/applications/).
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_complete_swagger_spec test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
