=begin
#Meltwater Streaming API v2

#The Meltwater Streaming API provides the needed resources for Meltwater clients to create & delete REST Hooks and stream Meltwater search results to your specified destination.

OpenAPI spec version: 2.0.0
Contact: support@api.meltwater.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PostV2Hooks
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PostV2Hooks' do
  before do
    # run before each test
    @instance = SwaggerClient::PostV2Hooks.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostV2Hooks' do
    it 'should create an instact of PostV2Hooks' do
      expect(@instance).to be_instance_of(SwaggerClient::PostV2Hooks)
    end
  end
  describe 'test attribute "target_url"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "search_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

