=begin
#Meltwater Streaming API v2

#The Meltwater Streaming API provides the needed resources for Meltwater clients to create & delete REST Hooks and stream Meltwater search results to your specified destination.

OpenAPI spec version: 2.0.0
Contact: support@api.meltwater.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/client_credentials'
require 'swagger_client/models/error'
require 'swagger_client/models/errors_collection'
require 'swagger_client/models/hook'
require 'swagger_client/models/hooks_collection'
require 'swagger_client/models/o_auth2_token'
require 'swagger_client/models/post_v2_hooks'
require 'swagger_client/models/search'
require 'swagger_client/models/searches_collection'

# APIs
require 'swagger_client/api/clients_api'
require 'swagger_client/api/hooks_api'
require 'swagger_client/api/oauth2_api'
require 'swagger_client/api/schemas_api'
require 'swagger_client/api/searches_api'
require 'swagger_client/api/swagger_doc_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
